[package]
name = "alloc_macro"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true
[dependencies]
buddy = {path = "../buddy"}
proc-macro2 = "1.0.84"
quote = "1.0.36"
syn = {version = "2.0.66", features = ["full"]}
